### ISSUE TITLE
update maps-0173_00000004 in OCFL

### ISSUE THREAD

**Issue by johnjung** [uchicago-library/mapping_chicagoland#1]
**Describe the bug**
maps-0173_00000004.tif needed to be rescanned. This has been completed, and the updated image is available in pres-xfer/mappingchicagoland/UChicago/UChicago_batch1/0173/TIFF/. @johnjung should validate the image, update the file in OCFL and alert @maddiealft, who will let XL know she can proceed with georeferencing.

**To Reproduce**
n/a

**Expected behavior**
See above.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by johnjung** [comment]
@maddiealft - I see the entire image in this scan, but the previous scan and the other three images in this map are approximately 420MB at 400ppi, but this one is 315MB at 348ppi. Additionally, the other TIFFs are single-page but this one is multi-page. Could you take a look at this one to check to be sure it matches our specs for the project? Thanks!

**Comment by maddiealft** [comment]
Hi John,

The other maps were scanned by a vendor and they were able to achieve the 400 dpi with their scanners. Unfortunately, we are not able to achieve that DPI in house due to the size of this map. I am not sure what you are referring to when you say this one is multi-page.

Thank you,
Madeline

Madeline Alft
Digital Grant Assistant
Digitization Unit | Preservation Department
The University of Chicago Library
1100 E. 57th St. Chicago, IL 60637
***@***.***
________________________________

**Comment by maddiealft** [comment]
@johnjung I accidentally replied via email. Are you able to see my response above? If not, I can resend it.

**Comment by johnjung** [comment]
@maddiealft - it's no problem about replying by email, I can see your response just fine. That's good to know about the resolution difference- I just wanted to confirm. 

Regarding multi-page TIFFs: the TIFF format lets you store more than one image in a given .tif file- each one is its own "page". In this case it looks like the second page is just a thumbnail, but if someone wanted they could put all of the page images for a single book into one TIFF. I'll proceed with this image as-is, but I'll also bring CM into our email thread separately so we can stay on top of things like that too.

Thanks very much- and thank you for your quick responses.

**Comment by maddiealft** [comment]
@johnjung Okay, interesting, Do you know how something like that happens? I am unable to see more than just the "image" when I open the file. I didn't do anything differently than I have been, but I wonder if this is something that happened with all of the maps I scanned. Is this something that you would  generally want to avoid? Or is it something that can be ignored? I apologize that this happened, like I said, I am not sure how I did it.

**Comment by johnjung** [comment]
No worries. In this case I bet the scanning software is adding the thumbnail pages. I know that some people in digital preservation try to avoid multi-page TIFFs, since they make migration more complicated. I'll send out a Zoom invite so we can figure out how to deal with this here.

**Comment by maddiealft** [comment]
@johnjung Hi John, I was able to separate the multi-page TIFF for maps-0173_00000004 but I think that this may be a larger issue. We have a solution, however it is quite slow and cumbersome and would require all the files to be reuploaded to the server. I think we can discuss this further in our meeting. 

I uploaded the single image to the folder, it is titles "maps-0173_00000004_page_0001". I believe this is the actual image and not the thumbnail.

**Comment by johnjung** [comment]
Hi @maddiealft -

The new image is now available through our IIIF server to AllMaps. I tested this by going to https://editor.allmaps.org/#/ and entering the IIIF manifest URL for maps-0173, https://iiif-collection.lib.uchicago.edu/object/ark:/61001/b2pk1v07c15r.json. 

Please pass this along to XL for geo-referencing. If the old blacked-out image still appears, you may need to shift-reload the page to get the new one to appear if the image has been cached. If you run into any trouble please let me know.

I'm going to close out this issue, but if you need to re-open it again for any reason please feel free.
